services:
  muse:
    image: codetheweb/muse:2.9.1
    container_name: muse
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      BOT_STATUS: online
      BOT_ACTIVITY_TYPE: PLAYING
      BOT_ACTIVITY: "music for the BEANS"
      CACHE_LIMIT: 2GB
    volumes:
      - ./muse:/data
